# Generated by Django 2.2.3 on 2021-07-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('correo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
