# Generated by Django 2.2.3 on 2021-07-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='contraseña',
            new_name='clave',
        ),
    ]
