# Generated by Django 2.2.3 on 2021-07-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='patent',
            new_name='patente',
        ),
    ]
