# Generated by Django 2.2.3 on 2021-07-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Registro'),
        ),
    ]
